### ISSUE TITLE
WARNING in graphite_1

### ISSUE THREAD

**Issue by luisnunezsalgado** [jjethwa/icinga2#114]
after executing the command docker-compose up, I've obtained the following WARNINGS in the graphite instance (logs in the console): 

```
lnunez@lnunez-Desktop:~/icinga2$ docker-compose up
Starting icinga2_icinga2_1
Starting icinga2_graphite_1
Attaching to icinga2_icinga2_1, icinga2_graphite_1
icinga2_1   | Site 000-default already enabled
graphite_1  | /usr/lib/python2.7/dist-packages/graphite/settings.py:234: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
graphite_1  |   warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
icinga2_1   | Site icingaweb2-ssl already disabled
icinga2_1   | Site icingaweb2-ssl-redirect already disabled
graphite_1  | System check identified some issues:
graphite_1  | 
graphite_1  | WARNINGS:
graphite_1  | ?: (1_6.W001) Some project unittests may not execute as expected.
graphite_1  | 	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
graphite_1  | Traceback (most recent call last):
graphite_1  |   File "/usr/bin/graphite-manage", line 15, in <module>
graphite_1  |     execute_from_command_line(sys.argv)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
graphite_1  |     utility.execute()
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
graphite_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
graphite_1  |     self.execute(*args, **options.__dict__)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 55, in execute
graphite_1  |     return super(Command, self).execute(*args, **options)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
graphite_1  |     output = self.handle(*args, **options)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 160, in handle
graphite_1  |     self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 187, in create_superuser
graphite_1  |     **extra_fields)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 178, in _create_user
graphite_1  |     user.save(using=self._db)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 589, in save
graphite_1  |     force_update=force_update, update_fields=update_fields)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 617, in save_base
graphite_1  |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 698, in _save_table
graphite_1  |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 731, in _do_insert
graphite_1  |     using=using, raw=raw)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
graphite_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
graphite_1  |     return query.get_compiler(using=using).execute_sql(return_id)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
graphite_1  |     cursor.execute(sql, params)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
graphite_1  |     return self.cursor.execute(sql, params)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
graphite_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
graphite_1  |     return self.cursor.execute(sql, params)
graphite_1  |   File "/usr/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 485, in execute
graphite_1  |     return Database.Cursor.execute(self, query, params)
graphite_1  | django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
graphite_1  | Starting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
graphite_1  | httpd (pid 34) already running
icinga2_1   | Starting MariaDB database server: mysqld.
icinga2_1   | warning/cli: Feature 'ido-mysql' already enabled.
icinga2_1   | warning/cli: Feature 'livestatus' already enabled.
icinga2_1   | warning/cli: Feature 'compatlog' already enabled.
icinga2_1   | warning/cli: Feature 'command' already enabled.
icinga2_1   | chfn: name with non-ASCII characters: 'Icinga2 MetroValparaíso'
icinga2_1   | => Enabling Icinga2 graphite writer
icinga2_1   | warning/cli: Feature 'graphite' already enabled.
icinga2_1   | Module path "/etc/icingaweb2/userModules" does not exist
icinga2_1   | Module path "/etc/icingaweb2/userModules" does not exist
icinga2_1   | Module path "/etc/icingaweb2/userModules" does not exist
icinga2_1   | => Enabling Icingaweb2 graphite module
icinga2_1   | Module path "/etc/icingaweb2/userModules" does not exist
icinga2_1   | 
icinga2_1   | ===================================================================
icinga2_1   | MySQL user 'root' has no password but only allows local connections
icinga2_1   | MySQL user 'icinga' password set to Jbg1TQJtbSKMgPZ
icinga2_1   | MySQL user 'icinga2-ido-mysq' password set to fUyX5SEvDttXGfp
icinga2_1   | MySQL user 'icingaweb2' password set to HoL3zUV2hDPPv6Y
icinga2_1   | MySQL user 'director' password set to I04f9LSq1SgIWb6
icinga2_1   | Director API password set to 0NQQbYCgTbl3JXI
icinga2_1   | 
icinga2_1   | Graphite writer enabled and sending data to carbon agent at: graphite:2003
icinga2_1   | 
icinga2_1   | Icinga Web 2 (/icingaweb2) default credentials: icingaadmin:icinga
icinga2_1   | ===================================================================
icinga2_1   | 
icinga2_1   | Starting Supervisor.
icinga2_1   | information/cli: Icinga application loader (version: r2.7.0-1)
icinga2_1   | information/cli: Loading configuration file(s).
icinga2_1   | information/ConfigItem: Committing config item(s).
icinga2_1   | information/ApiListener: My API identity: icinga2
icinga2_1   | warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
icinga2_1   | warning/ApplyRule: Apply rule 'ssh' (in /etc/icinga2/conf.d/services.conf: 47:1-47:19) for type 'Service' does not match anywhere!
icinga2_1   | information/ConfigItem: Instantiated 2 ApiUsers.
icinga2_1   | information/ConfigItem: Instantiated 1 ApiListener.
icinga2_1   | information/ConfigItem: Instantiated 1 Zone.
icinga2_1   | information/ConfigItem: Instantiated 1 FileLogger.
icinga2_1   | information/ConfigItem: Instantiated 1 Endpoint.
icinga2_1   | information/ConfigItem: Instantiated 2 NotificationCommands.
icinga2_1   | information/ConfigItem: Instantiated 12 Notifications.
icinga2_1   | information/ConfigItem: Instantiated 207 CheckCommands.
icinga2_1   | information/ConfigItem: Instantiated 1 Downtime.
icinga2_1   | information/ConfigItem: Instantiated 1 Host.
icinga2_1   | information/ConfigItem: Instantiated 1 IcingaApplication.
icinga2_1   | information/ConfigItem: Instantiated 2 HostGroups.
icinga2_1   | information/ConfigItem: Instantiated 1 UserGroup.
icinga2_1   | information/ConfigItem: Instantiated 3 TimePeriods.
icinga2_1   | information/ConfigItem: Instantiated 1 User.
icinga2_1   | information/ConfigItem: Instantiated 11 Services.
icinga2_1   | information/ConfigItem: Instantiated 3 ServiceGroups.
icinga2_1   | information/ConfigItem: Instantiated 1 ScheduledDowntime.
icinga2_1   | information/ConfigItem: Instantiated 1 CompatLogger.
icinga2_1   | information/ConfigItem: Instantiated 1 ExternalCommandListener.
icinga2_1   | information/ConfigItem: Instantiated 1 GraphiteWriter.
icinga2_1   | information/ConfigItem: Instantiated 1 IdoMysqlConnection.
icinga2_1   | information/ConfigItem: Instantiated 1 LivestatusListener.
icinga2_1   | information/ConfigItem: Instantiated 1 NotificationComponent.
icinga2_1   | information/ConfigItem: Instantiated 1 CheckerComponent.
icinga2_1   | information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
icinga2_1   | information/cli: Finished validating the configuration file(s).
icinga2_1   | 2017-10-19 13:32:24,335 CRIT Supervisor running as root (no user in config file)
icinga2_1   | 2017-10-19 13:32:24,335 INFO Included extra file "/etc/supervisor/conf.d/apache2.conf" during parsing
icinga2_1   | 2017-10-19 13:32:24,335 INFO Included extra file "/etc/supervisor/conf.d/fatalservicelistener.conf" during parsing
icinga2_1   | 2017-10-19 13:32:24,335 INFO Included extra file "/etc/supervisor/conf.d/icinga2.conf" during parsing
icinga2_1   | 2017-10-19 13:32:24,335 INFO Included extra file "/etc/supervisor/conf.d/mysql.conf" during parsing
icinga2_1   | Unlinking stale socket /var/run/supervisor.sock
icinga2_1   | 2017-10-19 13:32:24,641 INFO RPC interface 'supervisor' initialized
icinga2_1   | 2017-10-19 13:32:24,641 CRIT Server 'unix_http_server' running without any HTTP authentication checking
icinga2_1   | 2017-10-19 13:32:24,641 INFO supervisord started with pid 446
icinga2_1   | 2017-10-19 13:32:25,643 INFO spawned: 'fatalservice' with pid 449
icinga2_1   | 2017-10-19 13:32:25,644 INFO spawned: 'mysql' with pid 450
icinga2_1   | 2017-10-19 13:32:25,645 INFO spawned: 'apache2' with pid 451
icinga2_1   | 2017-10-19 13:32:25,645 INFO spawned: 'icinga2' with pid 452
icinga2_1   | READY
icinga2_1   | Starting Apache httpd web server: apache2checking Icinga2 configurationStarting MariaDB database server: mysqld already running.
icinga2_1   | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
icinga2_1   | .
icinga2_1   | Starting icinga2 monitoring daemon: icinga2[2017-10-19 13:32:25 +0000] information/cli: Icinga application loader (version: r2.7.0-1)
icinga2_1   | [2017-10-19 13:32:25 +0000] information/cli: Loading configuration file(s).
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Committing config item(s).
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ApiListener: My API identity: icinga2
icinga2_1   | [2017-10-19 13:32:25 +0000] warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
icinga2_1   | [2017-10-19 13:32:25 +0000] warning/ApplyRule: Apply rule 'ssh' (in /etc/icinga2/conf.d/services.conf: 47:1-47:19) for type 'Service' does not match anywhere!
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 ApiListener.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 Zone.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 FileLogger.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 Endpoint.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 12 Notifications.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 207 CheckCommands.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 Downtime.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 Host.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 2 HostGroups.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 UserGroup.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 3 TimePeriods.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 User.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 11 Services.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 3 ServiceGroups.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 ScheduledDowntime.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 CompatLogger.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 ExternalCommandListener.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 GraphiteWriter.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 LivestatusListener.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigObject: Restoring program state from file '/var/lib/icinga2/icinga2.state'
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigObject: Restored 260 objects. Loaded 0 new objects without state.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ConfigItem: Triggering Start signal for config items
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ApiListener: 'api' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ApiListener: Adding new listener on port '5665'
icinga2_1   | [2017-10-19 13:32:25 +0000] information/CompatLogger: 'compatlog' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/ExternalCommandListener: 'command' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/GraphiteWriter: 'graphite' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/DbConnection: 'ido-mysql' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/LivestatusListener: 'livestatus' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/LivestatusListener: Created UNIX socket in '/run/icinga2/cmd/livestatus'.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/NotificationComponent: 'notification' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] information/CheckerComponent: 'checker' started.
icinga2_1   | [2017-10-19 13:32:25 +0000] critical/TcpSocket: Invalid socket: Connection refused
icinga2_1   | Context:
icinga2_1   | 	(0) Reconnecting to Graphite 'graphite'
icinga2_1   | 
icinga2_1   | .
icinga2_1   | .
icinga2_1   | 2017-10-19 13:32:26,722 INFO success: fatalservice entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
icinga2_1   | 2017-10-19 13:32:26,722 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
icinga2_1   | 2017-10-19 13:32:26,722 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
icinga2_1   | 2017-10-19 13:32:26,722 INFO success: icinga2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
graphite_1  |  failed!
graphite_1  | The apache2 instance did not start within 20 seconds. Please read the log files to discover problems ... (warning).
graphite_1  | Starting Graphite backend daemon: carbon-cache.
icinga2_graphite_1 exited with code 0
```

Edit: Added code tags. Please use code tags the next time!

**Comment by bebehei** [comment]
> graphite_1  | django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username

Well it seems, that graphite fucked up.

- Which image do you use?

It's a weird bug. I never updated the `bebehei/graphite` image, so it can't be the case, that it used jango =< 1.5.

**Comment by jjethwa** [comment]
@luisnunezsalgado 

Try pulling up the logs for icinga2_graphite_1, it might give you more information to go on

**Comment by luisnunezsalgado** [comment]
@bebehei trying to clarify what is the issue, it seems that the image

    image: bebehei/graphite:latest

is using the jango ='1.7.11'

These are the commands executed: 

lnunez@lnunez-Desktop:~/icingatest/graphite$ docker exec -it graphite_graphite_1 /bin/bash
root@graphite:/# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.get_version()
'1.7.11'
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> quit()
root@graphite:/# whereis python
python: /usr/bin/python /usr/bin/python2.7 /usr/lib/python2.6 /usr/lib/python2.7 /etc/python /etc/python2.7 /usr/local/lib/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz
root@graphite:/#

**Comment by luisnunezsalgado** [comment]
I'm trying to play with the Dockerfile of bebehei/graphite:latest

https://hub.docker.com/r/bebehei/graphite/~/dockerfile/

getting the following: 

lnunez@lnunez-Desktop:~/icingatest/graphite-test$ docker build -t test .
Sending build context to Docker daemon   2.56kB
Step 1/6 : FROM debian
 ---> 874e27b628fd
Step 2/6 : RUN apt-get update     && apt-get -qy upgrade      && DEBIAN_FRONTEND=noninteractive apt-get -qy install         apache2         graphite-carbon         graphite-web         libapache2-mod-wsgi     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Running in 5720388ae90f
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://deb.debian.org/debian stretch Release [118 kB]
Get:4 http://security.debian.org stretch/updates InRelease [62.9 kB]
Get:5 http://deb.debian.org/debian stretch-updates/main amd64 Packages [5841 B]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2479 B]
Get:7 http://security.debian.org stretch/updates/main amd64 Packages [225 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.0 MB in 15s (659 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package graphite-web is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'graphite-web' has no installation candidate
The command '/bin/sh -c apt-get update     && apt-get -qy upgrade      && DEBIAN_FRONTEND=noninteractive apt-get -qy install         apache2         graphite-carbon         graphite-web         libapache2-mod-wsgi     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
lnunez@lnunez-Desktop:~/icingatest/graphite-test$ cat Dockerfile 
FROM debian

RUN apt-get update \
    && apt-get -qy upgrade  \
    && DEBIAN_FRONTEND=noninteractive apt-get -qy install \
        apache2 \
        graphite-carbon \
        graphite-web \
        libapache2-mod-wsgi \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cp /usr/share/graphite-web/apache2-graphite.conf /etc/apache2/sites-available/graphite.conf \
    && a2ensite graphite \
    && a2dissite 000-default

# Current docker version of Ubuntu xenial does not allow input onto rootfs, so two ADDs have to be used.
ADD run.sh /srv/run.sh
ADD default-graphite-carbon /etc/default/graphite-carbon

CMD /srv/run.sh
lnunez@lnunez-Desktop:~/icingatest/graphite-test$

**Comment by bebehei** [comment]
> E: Package 'graphite-web' has no installation candidate

I tried to port the debian image from debian jessie to stretch. This was also one issue I've seen. But the image from dockerhub is still the built with jessie and works (I use it on my workplace).

I gave up on porting and searched for other graphite images. I found one, which is more functional, smaller and better maintained and I will switch there in (near?) future.

So, I'm not planning to update the image ever. If you find another working image, we'd happily accept a PR with an improved `docker-compose.yml` file.

**Comment by luisnunezsalgado** [comment]
@bebehei thanks for your words, but I've made some changes into: https://github.com/bebehei/graphite-docker in order to receive your approval. 

I've included a fixed file of django.py, and also created a docker-composite.yml.

Have a good day.

**Comment by bebehei** [comment]
Many thanks to @hansij66, who contributed in #159 the necessary config to switch the docker container.

to all others: If you experience this issue, crawl the [current `docker-compose.yml`](https://github.com/jjethwa/icinga2/tree/ee6cdf5f4ff214affbfc7e47d6b75570f527e93f/docker-compose.yml) and copy the new graphite container description.
