### ISSUE TITLE
PHP error when create new service

### ISSUE THREAD

**Issue by dangmocrang** [jjethwa/icinga2#124]
First time use the docker image and I have issue when create new service as below. Is someone have same issue?
```
Method eventuallyAddNameRestriction does not exist

#0 /usr/local/share/icingaweb2/modules/director/application/forms/IcingaServiceForm.php(347): Zend_Form->__call('eventuallyAddNa...', Array)
#1 /usr/local/share/icingaweb2/modules/director/application/forms/IcingaServiceForm.php(267): Icinga\Module\Director\Forms\IcingaServiceForm->addNameElement()
#2 /usr/local/share/icingaweb2/modules/director/application/forms/IcingaServiceForm.php(70): Icinga\Module\Director\Forms\IcingaServiceForm->setupHostRelatedElements()
#3 /usr/local/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(356): Icinga\Module\Director\Forms\IcingaServiceForm->setup()
#4 /usr/local/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(517): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#5 /usr/local/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(530): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#6 /usr/local/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#7 /usr/local/share/icingaweb2/modules/director/application/controllers/ServiceController.php(162): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ServiceController->editAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('editAction')
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}
```

**Comment by dangmocrang** [comment]
Update to latest git master fixed the issue :)

**Comment by subinmath** [comment]
![screen shot 2018-01-09 at 2 22 33 pm](https://user-images.githubusercontent.com/17119174/34712382-ae01a786-f548-11e7-97ae-33a6cea291e5.png)
![screen shot 2018-01-09 at 2 24 24 pm](https://user-images.githubusercontent.com/17119174/34712432-d16ba262-f548-11e7-8b35-a3a62d68b176.png)
