### ISSUE TITLE
Web server error after login

### ISSUE THREAD

**Issue by ImplicitDeny** [jjethwa/icinga2#179]
Hi there,

I'm using the docker container on a Hypriot-geared Rasperrby PI. Icinga is deployed using Portainer, and configured to use an external DB shipped on an other container. When the container is starting, I cannot see any trouble in the logs, and the link to MySQL is properly established (tables are created, etc).

However when I try to access the web interface, I encounter a problem with the web server. I can successfully login with default credentials, but after login there is an uncaught exception in Response.php, making the interface not to display.

You can find here the full (and not so pretty) error message :
<details><summary>Hidden</summary><p>

```
Fatal error: Uncaught ErrorException: setcookie() expects parameter 3 to be integer, float given in /usr/share/php/Icinga/Web/Response.php:317 Stack trace: #0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'setcookie() exp...', '/usr/share/php/...', 317, Array) #1 /usr/share/php/Icinga/Web/Response.php(317): setcookie('icingaweb2-anno...', '{"acknowledged"...', 2147483648, '/icingaweb2/', NULL, false, true) #2 /usr/share/php/Icinga/Web/Response.php(329): Icinga\Web\Response->sendCookies() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response->sendHeaders() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract->sendResponse() #5 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #6 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch() #7 /usr/share/icingaweb in /usr/share/php/Icinga/Web/Response.php on line 317
```

</p></details>

I can't find any intel on this problem. Do I miss something ? The container seems to be fully deployed.
Thanks

**Comment by jjethwa** [comment]
Hi @ImplicitDeny 

Can you provide the docker run command?  Are you using any volumes?  What version of the container are you using?

**Comment by cobrafast** [comment]
I've got the same problem after building the image on my RPi4 today. Git clone and `docker build --no-cache .` went through without problems. I manually tagged it as `jordan/icinga2:latest-armhf` afterwards.

The run command I used:
```bash
docker run \
        -p 8080:80 \
        -h icinga2 \
        -t \
        -v /root/docker/icinga2-etc:/etc/icinga2 \
        jordan/icinga2:latest-armhf
```
---
```
Fatal error: Uncaught ErrorException: setcookie() expects parameter 3 to be integer, float given in /usr/share/php/Icinga/Web/Response.php:317
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'setcookie() exp...', '/usr/share/php/...', 317, Array) 
#1 /usr/share/php/Icinga/Web/Response.php(317): setcookie('icingaweb2-anno...', '{"acknowledged"...', 2147483648, '/icingaweb2/', NULL, false, true) 
#2 /usr/share/php/Icinga/Web/Response.php(329): Icinga\Web\Response->sendCookies() 
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response->sendHeaders() 
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract->sendResponse() 
#5 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) 
#6 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch() 
#7 /usr/share/icingaweb in /usr/share/php/Icinga/Web/Response.php on line 317
```

**Comment by jjethwa** [comment]
Hi @cobrafast 

I'm wondering if it's related to this issue: https://github.com/Icinga/icingaweb2/issues/3459
