### ISSUE TITLE
Unable to detect your deployment endpoint. I was looking for the first endpoint configured with an assigned API user in the "master" zone.

### ISSUE THREAD

**Issue by roflmao** [jjethwa/icinga2#56]
Testing the latest "latest" tag the icinga2 doesnt approve login:

```
    Error

Unable to detect your deployment endpoint. I was looking for the first endpoint configured with an assigned API user in the "master" zone.

#0 /etc/icingaweb2/modules/director/library/Director/Db.php(165): Icinga\Module\Director\Db->getDeploymentEndpointName()
#1 /etc/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(363): Icinga\Module\Director\Db->getDeploymentEndpoint()
#2 /etc/icingaweb2/modules/director/application/controllers/ConfigController.php(110): Icinga\Module\Director\Web\Controller\ActionController->api()
#3 /usr/share/php/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\ConfigController->activitiesAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('activitiesActio...')
#5 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```

2.5.3 tag still works.

**Comment by jjethwa** [comment]
Hi @roflmao 

Sorry about that 😞   Are you using your own configs (via a volume)?

**Comment by bebehei** [comment]
Finally got the same error message. But this only happens after a restart as long as icingaweb2 director is not connected to icinga2. Fixed in less than a minute automatically.

@roflmao Do you experience this still on latest tag?

**Comment by bebehei** [comment]
Ok, I can finally reproduce this. @roflmao remove `/etc/icinga2/conf.d/api-users.conf` and reboot your container.

If the error still persists, look forward, that the passwords in `/etc/icinga2/conf.d/api-users.conf` and `/etc/icingaweb2/modules/director/kickstart.ini` match.

#67 will automatically fix this permanently.
