### ISSUE TITLE
PDF export does not work

### ISSUE THREAD

**Issue by bebehei** [jjethwa/icinga2#77]
I just had been curious, how a PDF-Page would look like. But there are some problems with dompdf:

But actually the package `php-dompdf` is installed.

```
Warning: Uncaught exception 'ErrorException' with message 'require_once(dompdf/autoload.inc.php): failed to open stream: No such file or directory' in /usr/share/php/Icinga/File/Pdf.php:12 Stack trace: #0 /usr/share/php/Icinga/File/Pdf.php(12): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(do...', '/usr/share/php/...', 12, Array) #1 /usr/share/php/Icinga/File/Pdf.php(12): require_once() #2 /usr/share/php/Icinga/Application/ClassLoader.php(306): require('/usr/share/php/...') #3 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\File\\Pdf') #4 /usr/share/php/Icinga/Web/Controller/ActionController.php(536): spl_autoload_call('Icinga\\File\\Pdf') #5 /usr/share/php/Icinga/Web/Controller/ActionController.php(481): Icinga\Web\Controller\ActionController->sendAsPdf() #6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(512): Icinga\Web\Controller\ActionController->postDispatch() #7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controll in /usr/share/php/Icinga/File/Pdf.php on line 12

Fatal error: main(): Failed opening required 'dompdf/autoload.inc.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/usr/share/php:/usr/share/pear') in /usr/share/php/Icinga/File/Pdf.php on line 12
```

**Comment by bebehei** [comment]
Testing this again on a merge-branch of #75 and #74 again. And there, works like a charm on a self-built image.

Not reproducable and seems to work -> closing.
